workers_dev = true
name = "pc-foundation"
compatibility_date = "2025-03-10"
main = "./workers/app.ts"
assets = { directory = "./build/client/" }
compatibility_flags = ["nodejs_compat"]

[vars]
VITE_BASE_URL = 'https://www.peace-coin.org'

[observability]
enabled = true

[env.development]
name = "pc-foundation-dev"

[env.development.vars]
VITE_BASE_URL = 'https://dev.peace-coin.org'

[env.development.observability]
enabled = true
