workers_dev = true
name = "pc-foundation"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]
main = "./workers/app.ts"
assets = { directory = "./build/client/" }

[observability]
enabled = true

[[kv_namespaces]]
binding = "KV"
id = "30b4166488744b9da52e3da65f926de0"

[env.development]
name = "pc-foundation-dev"


[env.development.observability]
enabled = true

[[env.development.kv_namespaces]]
binding = "KV"
id = "30b4166488744b9da52e3da65f926de0"