workers_dev = true
name = "pc-foundation"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]
main = "./workers/app.ts"
assets = { directory = "./build/client/" }

[vars]
CROWDIN_PROJECT_ID = "629106"

[[kv_namespaces]]
binding = "KV"
id = "30b4166488744b9da52e3da65f926de0"

[env.development]
name = "pc-foundation-dev"

[env.development.vars]
CROWDIN_PROJECT_ID = "629106"

[[env.development.kv_namespaces]]
binding = "KV"
id = "30b4166488744b9da52e3da65f926de0"