workers_dev = true
name = "pc-foundation"
compatibility_date = "2025-03-10"
main = "./workers/app.ts"
assets = { directory = "./build/client/" }

[observability]
enabled = true

[env.development]
name = "pc-foundation-dev"

[env.development.observability]
enabled = true
